### PR TITLE
Remove NSURLProtocol, replaced by NSURLSession & NSURLConnection method swizzle

### PR DESCRIPTION
**Pull request by kagenZhao**
Remove NSURLProtocol, replaced by NSURLSession & NSURLConnection method swizzle.
Support download & upload progress call back,
Fix Last PR crash when request url is nil and when dataTask completionHandler is nil.
Add tests in objc_example & swift_example programe.
Cannot support ASIHTTPRequest (by CFNetwork, NSURLProtocol also cannot support that).

Please review again.

### CODE REVIEW

**Comment by CocoaDebug** [comment]
I found a bug.
Simulator Screen Shot - iPhone Xʀ - 2020-09-05 at 13 27 08

**Comment by kagenZhao** [comment]
I did not reproduce this, please tell me how you did it?  This can help me solve this bug.

simulator_screenshot_2E201E6D-731F-421F-8432-AB23BA01C331

**Comment by CocoaDebug** [comment]
Xcode clean project, and run again.

**Comment by kagenZhao** [comment]
I see, the cache data of my last request is not cleared.

**Comment by kagenZhao** [comment]
Thank you for helping me test. Some problems will always be undetectable. 
I have a suggestion. You can create a development branch so that we don’t have to repeat PR

**Comment by CocoaDebug** [comment]
Good idea!
I have created a development branch now.

**Pull request merged**
